  export const genreOptions = [
    {
      name: "Action",
      value: "Action",
      type: "genres",
    },
    {
      name: "Adventure",
      value: "Adventure",
      type: "genres",
    },
    {
      name: "Comedy",
      value: "Comedy",
      type: "genres",
    },
    {
      name: "Drama",
      value: "Drama",
      type: "genres",
    },
    {
      name: "Ecchi",
      value: "Ecchi",
      type: "genres",
    },
    {
      name: "Fantasy",
      value: "Fantasy",
      type: "genres",
    },
    {
      name: "Horror",
      value: "Horror",
      type: "genres",
    },
    {
      name: "Mahou Shoujo",
      value: "Mahou Shoujo",
      type: "genres",
    },
    {
      name: "Mecha",
      value: "Mecha",
      type: "genres",
    },
    {
      name: "Music",
      value: "Music",
      type: "genres",
    },
    {
      name: "Mystery",
      value: "Mystery",
      type: "genres",
    },
    {
      name: "Psychological",
      value: "Psychological",
      type: "genres",
    },
    {
      name: "Romance",
      value: "Romance",
      type: "genres",
    },
    {
      name: "Sci-Fi",
      value: "Sci-Fi",
      type: "genres",
    },
    {
      name: "Slice of Life",
      value: "Slice of Life",
      type: "genres",
    },
    {
      name: "Sports",
      value: "Sports",
      type: "genres",
    },
    {
      name: "Supernatural",
      value: "Supernatural",
      type: "genres",
    },
    {
      name: "Thriller",
      value: "Thriller",
      type: "genres",
    },
  ];

  export const tagsOptions = [
    { name: "Afterlife", value: "Afterlife", type: "tags" },
    { name: "Anti-Hero", value: "Anti-Hero", type: "tags" },
    { name: "Basketball", value: "Basketball", type: "tags" },
    { name: "Battle Royale", value: "Battle Royale", type: "tags" },
    { name: "Cars", value: "Cars", type: "tags" },
    { name: "College", value: "College", type: "tags" },
    { name: "Delinquents", value: "Delinquents", type: "tags" },
    { name: "Demons", value: "Demons", type: "tags" },
    { name: "Fairy Tale", value: "Fairy Tale", type: "tags" },
    { name: "Family Life", value: "Family Life", type: "tags" },
    { name: "Food", value: "Food", type: "tags" },
    { name: "Gambling", value: "Gambling", type: "tags" },
    { name: "Ghost", value: "Ghost", type: "tags" },
    { name: "Gore", value: "Gore", type: "tags" },
    { name: "Harem", value: "Harem", type: "tags" },
    { name: "Historical", value: "Historical", type: "tags" },
    { name: "Idol", value: "Idol", type: "tags" },
    { name: "Isekai", value: "Isekai", type: "tags" },
    { name: "Iyashikei", value: "Iyashikei", type: "tags" },
    { name: "Josei", value: "Josei", type: "tags" },
    { name: "Kids", value: "Kids", type: "tags" },
    { name: "Mafia", value: "Mafia", type: "tags" },
    { name: "Magic", value: "Magic", type: "tags" },
    { name: "Martial Arts", value: "Martial Arts", type: "tags" },
    { name: "Military", value: "Military", type: "tags" },
    { name: "Musical", value: "Musical", type: "tags" },
    { name: "Mythology", value: "Mythology", type: "tags" },
    { name: "Nudity", value: "Nudity", type: "tags" },
    { name: "Parody", value: "Parody", type: "tags" },
    { name: "Philosophy", value: "Philosophy", type: "tags" },
    { name: "Post-Apocalyptic", value: "Post-Apocalyptic", type: "tags" },
    { name: "Reincarnation", value: "Reincarnation", type: "tags" },
    { name: "Revenge", value: "Revenge", type: "tags" },
    { name: "Reverse Harem", value: "Reverse Harem", type: "tags" },
    { name: "Samurai", value: "Samurai", type: "tags" },
    { name: "School", value: "School", type: "tags" },
    { name: "Seinen", value: "Seinen", type: "tags" },
    { name: "Shoujo", value: "Shoujo", type: "tags" },
    { name: "Shoujo Ai", value: "Shoujo Ai", type: "tags" },
    { name: "Shounen", value: "Shounen", type: "tags" },
    { name: "Shounen Ai", value: "Shounen Ai", type: "tags" },
    { name: "Super Power", value: "Super Power", type: "tags" },
    { name: "Superhero", value: "Superhero", type: "tags" },
    { name: "Survival", value: "Survival", type: "tags" },
    { name: "Swordplay", value: "Swordplay", type: "tags" },
    { name: "Teacher", value: "Teacher", type: "tags" },
    { name: "Terrorism", value: "Terrorism", type: "tags" },
    { name: "Time Skip", value: "Time Skip", type: "tags" },
    { name: "Tragedy", value: "Tragedy", type: "tags" },
    { name: "Vampire", value: "Vampire", type: "tags" },
    { name: "Video Games", value: "Video Games", type: "tags" },
    { name: "Zombie", value: "Zombie", type: "tags" },
  ];

  export const formatOptions = [
    { name: "TV", value: "TV" },
    { name: "TV Short", value: "TV_SHORT" },
    { name: "Movie", value: "MOVIE" },
    { name: "Special", value: "SPECIAL" },
    { name: "OVA", value: "OVA" },
    { name: "ONA", value: "ONA" },
  ];

  export const sortbyOptions = [
    { name: "Date Added", value: "ID_DESC" },
    { name: "Title", value: "TITLE_ENGLISH" },
    { name: "Release Date", value: "START_DATE_DESC" },
    { name: "Average Score", value: "SCORE_DESC" },
    { name: "Popularity", value: "POPULARITY_DESC" },
    { name: "Trending", value: "TRENDING_DESC" },
    { name: "Favorites", value: "FAVOURITES_DESC" },
  ];
  export const yearOptions = [
    { name: "1998", value: "1998" },
    { name: "1999", value: "1999" },
    { name: "2000", value: "2000" },
    { name: "2001", value: "2001" },
    { name: "2002", value: "2002" },
    { name: "2003", value: "2003" },
    { name: "2004", value: "2004" },
    { name: "2005", value: "2005" },
    { name: "2006", value: "2006" },
    { name: "2007", value: "2007" },
    { name: "2008", value: "2008" },
    { name: "2009", value: "2009" },
    { name: "2010", value: "2010" },
    { name: "2011", value: "2011" },
    { name: "2012", value: "2012" },
    { name: "2013", value: "2013" },
    { name: "2014", value: "2014" },
    { name: "2015", value: "2015" },
    { name: "2016", value: "2016" },
    { name: "2017", value: "2017" },
    { name: "2018", value: "2018" },
    { name: "2019", value: "2019" },
    { name: "2020", value: "2020" },
    { name: "2021", value: "2021" },
    { name: "2022", value: "2022" },
    { name: "2023", value: "2023" },
    { name: "2024", value: "2024" },
  ];
  export const seasonOptions = [
    { name: "Winter", value: "WINTER" },
    { name: "Spring", value: "SPRING" },
    { name: "Summer", value: "SUMMER" },
    { name: "Fall", value: "FALL" },
  ];

export const airingOptions = [
    { name: "Releasing", value: "RELEASING" },
    { name: "Not Yet Released", value: "NOT_YET_RELEASED" },
    { name: "Finished", value: "FINISHED" },
    { name: "Cancelled", value: "CANCELLED" },
  ];